govuk-one-login/observability-configuration

.github/workflows/deploy.yml
.gitignore
README.md
dashboards.tf
dashboards/signin-signup.json
groups.tf

Adds functionality to create dashboards in Terraform.
Example Sign In/Sign Up dashboard, with permissions and groups (from data sources).
This adds the requirement for the pipeline to have an OAuth client configured as secrets (`DT_ACCOUNT_ID`, `DT_CLIENT_ID` and `DT_CLIENT_SECRET`)

Add Sign In/Sign Up dashboard

---

dashboards/DORA Metrics Dashboard.json

PLAT-3142
Exported DORA dashboard from dynatrace as a back up json file.
Deployment Frequency:
Change Failure Rate:
Lead Time for Change:

plat-3142 Exported dora metrics dashboard as a back up

---

alerting_profiles.tf
data.tf
problem_notifications.tf
service_detection.tf

OBS-186 fix existing code add external web requests and unified services endpoint metrics
Also terraform format: alerting_profiles.tf, data.tf and problem_notifications.tf
[OBS-186]
[OBS-186]: https://govukverify.atlassian.net/browse/OBS-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OBS-186 fix existing code and add extra resources

---

problem_notifications.tf

The alerting profile reference should be the ID of the resource, not free text
[OBS-199]
[OBS-199]: https://govukverify.atlassian.net/browse/OBS-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change to referencing the alerting profile

---

dashboards.tf

So that teams can't ClickOps dashboards managed by Terraform, causing state issues.
[INCIDEN-653]
[INCIDEN-653]: https://govukverify.atlassian.net/browse/INCIDEN-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove EDIT access to dashboards managed by Terraform

---

.terraform.lock.hcl
mzs.tf

Adds a filter to each MZ to filter metrics with a dimension of `aws.account.id`, so those metrics will appear in the MZ view in Data Explorer.
[OBS-242]
[OBS-242]: https://govukverify.atlassian.net/browse/OBS-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add dimension filter to each AWS account MZ, filtering for aws.account.id

---

dashboards/signin-signup.json

Driving License CRI was not included on the list. Also fixes an outstanding issue that non-prod versions of these tiles are unpopulated.

Make the queries of the credentials issued tiles more generic.

---

settings_service_mzs.tf

Clean up MZ definition, prepend an [AWS] prefix to them.

Clean up MZ definition, prepend an [AWS] prefix to them.

---

.github/workflows/check.yml
dashboards/aws_service_quotas.json

Removing the ID and metadata from the `aws_service_quotas.json` dashboard added in #61, which is causing [terraform apply](https://github.com/govuk-one-login/observability-configuration/actions/runs/8186441487) to fail.
Also add a job to the pre-merge checks to confirm that no dashboard JSON definitions contain an ID, to prevent similar failures on merge.
Check action tested:
- [Expected failure](https://github.com/govuk-one-login/observability-configuration/actions/runs/8187341935)
- [Expected success](https://github.com/govuk-one-login/observability-configuration/actions/runs/8187358849)
[QA-417]
[QA-417]: https://govukverify.atlassian.net/browse/QA-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[QA-417] Strip dashboard ID and add pre-merge check

---

dashboards/aws_service_quotas.json

Updating metric sources and queries to use the metric stream metrics as the source
```diff
- ext:cloud.aws.usage.callCountSumByClassResourceType
+ cloud.aws.usage.callCountByAccountIdClassRegionResourceServiceType
```
QA-467

[QA-467] Update metric sources for AWS Service Quota dashboard

---

modules/monitors/webchat/monitor.tf
modules/monitors/webchat/site.tf
modules/monitors/webchat/variables.tf
monitors.tf

We are introducing a JS widget on the contact page that will load a webchat client. This will give users another route to get support from One Login.
The webchat is a service hosted by one of our suppliers and we have limited monitoring available to us.
Add a new browser monitor that loads the English and Welsh contact pages and waits for the 'start webchat' button to appear. This button is injected by the JS, so once it appears we know that our supplier's origin is up and that the webchat has successfully loaded enough for a user to open the chat. The monitor will timeout and fail if the button's not appeared after 10 seconds. 
The English and Welsh chats are deployed as two separate applications by our supplier, so it's necessary to load both languages.
The monitor is configured to …

OLH-1698: Add browser monitor for webchat widget

---

settings_service_detection.tf

Added in missing service detection rule for Experian.
PSREOBS-161 (noticed while creating the Service Dashboard)

Added missing detection rule for Experian

---

dashboards.tf
dashboards/authentication/account-interventions-integration.json
dashboards/authentication/account-interventions-prod.json
dashboards/authentication/account-interventions-staging.json

Adds dashboards for authentication's interaction with the account interventions service, similar to orchestration's dashboards (exact information presented differs slightly).
AUT-2688
Equivalent PR adding similar for orchestration: https://github.com/govuk-one-login/observability-configuration/pull/118

AUT-2688: Add authentication account interventions dashboards

---

modules/web_application/data_privacy.tf
modules/web_application/detection.tf
modules/web_application/main.tf
modules/web_application/site.tf
modules/web_application/variables.tf
web_applications.tf

Will enable RUM for `signin.staging.account.gov.uk` with opt-in mode disabled for testing.
[PSREOBS-198]
[PSREOBS-198]: https://govukverify.atlassian.net/browse/PSREOBS-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add web_application module and create module instance for staging

---

dashboards.tf
dashboards/authentication/di-auth-check-experian/di-auth-check-experian.json.tpl
dashboards/authentication/di-auth-check-experian/main.tf
dashboards/authentication/di-auth-check-experian/site.tf
dashboards/authentication/di-auth-check-experian/variables.tf

Create a dashboard from a template for `build`, `staging`, `integration` and `production` environments. This allows us a place to gain an insight into the internal workings of the check-experian features.
These dashboards are expected to be augmented as we develop the new featuresets.
[AUT-2274](https://govukverify.atlassian.net/browse/AUT-2274?atlOrigin=eyJpIjoiNTI2N2Y0MGMyZWE5NGJiZWFiNDdlMzRiYzEyMTUzNTAiLCJwIjoiaiJ9)
[AUT-2274]: https://govukverify.atlassian.net/browse/AUT-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create `di-auth-check-experian` dashboards

---

dashboards/account-interventions-service/account_interventions_service_dashboard.json

Update Dynatrace Dashboard queries that use ext: to cloud.aws instead 
[OBS-XXX]
ATB-1593

ATB-1593 | Update Dynatrace Dashboard queries that use ext: to cloud.aws instead

---

dashboards-cloudfront.tf

AUT-2766- Adding Auth team to monitor traffic to cloudfront on Dynatrace Dashboard
AUT-2766

AUT-2766- Adding Auth team to cloudfront Dashboard

---

dashboards.tf
dashboards/orange/dashboard-builder/main.tf
dashboards/orange/dashboard-builder/templates/check-hmrc-cri.tpl.json
dashboards/orange/dashboard-builder/templates/check-hmrc-lambda-metrics.tpl.json
dashboards/orange/dashboard-builder/variables.tf

added orange dashboards for Check HMRC CRI (NINO).
[OJ-2493]https://govukverify.atlassian.net/browse/OJ-2493
[OJ-2493]: https://govukverify.atlassian.net/browse/OJ-2493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added orange dashboards for Check HMRC CRI.

---

dashboards/orange/dashboard-builder/templates/otg-cri.tpl.json
dashboards/orange/dashboard-builder/templates/otg-lambda-metrics.tpl.json

fix orange otg dashboards, removed id from templates.
[OJ-2496]https://govukverify.atlassian.net/browse/OJ-2496
[OJ-2496]: https://govukverify.atlassian.net/browse/OJ-2496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix orange otg dashboards, removed id from templates.

---

settings_anomaly_detection.tf

This alert is not that useful given we will be alerted for service errors for monitored lambdas.

Disable Lambda high error rate alert

---

dashboards-cloudfront.tf

Updates owneremail and teamname for the CF dashboards in Dynatrace
[KIWI-1846](https://govukverify.atlassian.net/browse/KIWI-1846)
[KIWI-1846]: https://govukverify.atlassian.net/browse/KIWI-1846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Kiwi CF Requests Dashboard

---

dashboards-cloudfront.tf

Adds orange CRIs to cloudfront dashboards as per https://govukverify.atlassian.net/wiki/spaces/DID/pages/4097146881/Dynatrace+dashboard+to+help+you+through+the+deployment
[OJ-2517]
[OJ-2517]: https://govukverify.atlassian.net/browse/OJ-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2517: Adds orange CRIs to cloudfront dashboards

---

dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json

New WAF tile on CloudFront monitoring dashboards
- this may help TSD or teams notice if there is a problem with the Cloaking WAF especially
- part of the CloudFront initiative involves some WAF complexity so having this on a purpose-built dashboard seems sensible
https://govukverify.atlassian.net/browse/PLAT-4403

Add WAF dashboard

---

dashboards-dora.tf
dashboards/dev-platform/TEMPLATE1_dashboard.json
dashboards/dev-platform/TEMPLATE2_dashboard.json
dashboards/dev-platform/TEMPLATE3_dashboard.json
dashboards/dev-platform/pipelines-list.csv
dashboards/dev-platform/template1.csv
dashboards/dev-platform/template2.csv
dashboards/dev-platform/template3.csv

Team specific pipeline DORA dashboards: 
1. show pipeline versions from failed deployments, previously the queries were filtered only to collect successful deployments
2. pipeline versions appear in ascending order, highlighting older versions first. 
Updates to observability-configuration/dashboards-dora.tf
1. Variables teams1, team2, team3 with default values replaced with csv files
3. Updated instructions to reflect the above changes
[PSREDEV-800]
**Cannot be fully tested unless the PR is merged. Terraform plans on the pre-merge checks look good.**
[PSREDEV-800]: https://govukverify.atlassian.net/browse/PSREDEV-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-800 - Refactoring dev-platform dora dashboard deployments

---

dashboards/dev-platform/pipelines-list.csv
dashboards/dev-platform/template2.csv

Fixing typo: name of passport-api samstackname
[PSREDEV-800]
[PSREDEV-800]: https://govukverify.atlassian.net/browse/PSREDEV-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-800 - Fixing typo: name of passport-api samstackname

---

settings_anomaly_detection.tf

Removal of Dyna metric events for ECS CPU & Memory reservation as they don't support ECS on AWS Fargate, they only support ECS on EC2.
[OBS-XXX]

Removal of ECS reservation custom alerts

---

dashboards/capacity/critical-conformance.json

Fixed the problem with CRITICAL not filtering just on the Critical packs.
[LS-2134]
[LS-2134]: https://govukverify.atlassian.net/browse/LS-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LS-2134 Fixed critical conformance pack filter

---

failure_detection.tf

Add ignore parameters and rules to Dynatrace failure detection for "Missing prereq for this step" error.
[PSREO-240]
[PSREO-240]: https://govukverify.atlassian.net/browse/PSREO-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREO-240 add ignore_missing_prereq_for_this_step to failure detection

---

dashboards/core/services.json
dashboards/kiwi/apigw-metrics.json
dashboards/kiwi/bav-cri.json
dashboards/kiwi/cic-cri.json
dashboards/kiwi/f2f-cri.json
dashboards/kiwi/ipr-cri.json
dashboards/kiwi/services.json

- Update the markdown links on the Core and KIWI dashboards. This will allow to delete the dev dashboards. 
[IPS-800]
[IPS-800]: https://govukverify.atlassian.net/browse/IPS-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-800: Update the markdown links on  the core and KIWI dashboards

---

dashboards.tf

This adds six dashboards for the load test:
- orch
- dcmaw
- passport
- address
- fraud
- kbv
[LS-2196]
[LS-2196]: https://govukverify.atlassian.net/browse/LS-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LS-2196 Add dashboards for monitoring production stubs for IPV (Passport) load tests

---

web_applications.tf

No consent mechanism has yet been configured, so while this will serve the RUM scripts (and allow us to test the impact of load times in the meantime), it won't actively monitor any users.
[OBS-XXX]

Enable RUM in staging for testing

---

dashboards.tf
dashboards/capacity/Auth-application-performance.json

Deploying Auth performance dashboard to include Redis Stats for performance test 
[AUT-2917]
- [yes ] Is my change backwards compatible? Please include evidence
- [ No] I have tested this and added output to Jira Comment: This is getting deployed in non-prod will be tested there 
[AUT-2917]: https://govukverify.atlassian.net/browse/AUT-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Deploy Auth performance monitoring Dashboard only in Non-prod

---

dashboards/team-idc-app.json

A cloned version of the prod dashboard was created, the .json in the PR is from that cloned dashboard.  The `ext:` metrics have been removed from the dashboard definition.
[PSREGOV-327]
[PSREGOV-327]: https://govukverify.atlassian.net/browse/PSREGOV-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed ext: metrics from Team dashboard

---

dashboards.tf
dashboards/spot/cimit-api-gateway.json

Added a dashboard to Dynatrace to monitor the Contra Indicators API Gateway.
* [SPT-798](https://govukverify.atlassian.net/browse/SPT-798)
[SPT-798]: https://govukverify.atlassian.net/browse/SPT-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SPT-798 Added CIMIT API Gateway Dashboard

---

dashboards/orange/address-cri.json
dashboards/orange/address-lambda-metrics.json

Updated Orange Address Dashboards to include Postcode Errors Tiles
[OJ-2647]
[OJ-2647]: https://govukverify.atlassian.net/browse/OJ-2647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2647: Updated Orange Address Dashboards to include Postcode Errors

---

dashboards.tf
dashboards/home/home-summary-dashboard.json

This dashboard has existed for a while (see [prod](https://bhe21058.live.dynatrace.com/#dashboard;id=9e93b74d-a0f1-49af-bc26-0542c4a5ee69;gf=-2169816534325381897;gtf=-2h) and [non-prod](https://khw46367.live.dynatrace.com/#dashboard;id=76f2d261-b02c-4f0e-8789-77afd4ebb090;gf=7933752704887239681;gtf=-2h)) but we've not saved the JSON here. Add the configuration so we can recreate it if we need to.
Once this PR has been deployed I expect it to create duplicate dashboards. I'll go in and delete the ones which were manually created so we only have the new ones managed by Terraform.

BAU: Add Home team summary dashboard

---

dashboards/orange/check-hmrc-lambda-metrics.json

Add graph for LatencyInMs for MatchingFunction in check-hmrc-cri-api
[OJ-2632]
[OJ-2632]: https://govukverify.atlassian.net/browse/OJ-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2632: Add `LatencyInMs` to dashboard for MatchingFunction

---

dashboards/spot/cimit-api-gateway.json

Add tiles to the existing CIMIT API Gateway dashboard that show the requests per second over time and maximum requests per second over a time period.
The data reported in these tiles are subject to the limitations of Dynatrace's resolution limits. I.e. over larger time periods Dynatrace uses a resolution that is greater, e.g. 5 minutes over 1 minute, and this leads to higher approximations for of the value of requests per second.
SPT-774

SPT-774 Update CIMIT API Gateway with requests per second

---

dashboards-dora.tf
dashboards/dev-platform/pipelines-list-multi-sam-stack-names.csv
dashboards/dev-platform/teams_pipeline_dora_dashboard_multiple_ssn.tftpl

PR to add DORA dashboards that enable:
- Pipelines using multiple sam stack names for a single application
- Teams to have multiple pipelines in a single dashboard
[PSREDEV-1259]
[PSREDEV-1266]
[PSREDEV-1259]: https://govukverify.atlassian.net/browse/PSREDEV-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSREDEV-1266]: https://govukverify.atlassian.net/browse/PSREDEV-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-1259: enable multiple sam stack name

---

dashboards/capacity/application-performance-review.json

In the `Performance BE & FE` dynatrace dashboard, the `Task Count by Service` panel shows the status of ECS tasks. This should also include Unhealthy Host Count to monitor if there are any unhealthy FE containers.
Metric Used - `cloud.aws.applicationelb.unHealthyHostCountByAccountIdLoadBalancerRegionTargetGroup`
[QA-559]
[QA-559]: https://govukverify.atlassian.net/browse/QA-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[QA-559]: Include Unhealthy Host Count in Perf BE & FE dashboard

---

dashboards/orange/address-lambda-metrics.json

We are capturing a new metric in Address CRI for post code lookups. This PR adds the metrics to the address lambda metrics dashboard. 
**Screenshot**: The new graph is LatencyInMs
[OJ-2745]
[OJ-2745]: https://govukverify.atlassian.net/browse/OJ-2745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2745: Add `latencyInMs` graph for postcode lookup function to Address Lambda Metrics

---

modules/web_application/error_rules.tf
modules/web_application/main.tf

Some of the HTTP error rules are currently being considered as part of Apdex ratings when they shouldn't be, this PR is to amend the currently defined settings against each of the deployed RUM applications
PSREGOV-1082

Addition of RUM http error rules

---

modules/web_application/error_rules.tf

Missed that the "error_codes" attribute is meant to be a String.
PSREGOV-1082

error_codes is meant to be a String

---

dashboards/encrypted-vc-storage/encrypted_vc_storage_dashboard.json

Updated EVCS dashboard to handle new VC_SAVED metric with provenance dimension added.
[ATB-1807]
[ATB-1807]: https://govukverify.atlassian.net/browse/ATB-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATB-1807: handle new VC_SAVED metric with provenance dimension added

---

modules/web_application/error_rules.tf
modules/web_application/main.tf

The Apdex scores for each RUM application is taking into account 97x Error Codes and CSP Violations are removed from Apdex ratings, but these are google analytics tagmanager errors and CSP inconsistencies between frontends, respectively, and should not be included in Apdex ratings. Use this ticket to remove the above mentioned error codes from consideration and identify what else is being included in Apdex ratings that can be removed.
As a Engineer
I want to filter out incorrect data from Apdex ratings So that the ratings being generated don’t contain user-generated errors And instead reflect the true definition of Apdex ratings for a web application
- 97x Error Codes are removed from Apdex ratings
- CSP Violations are removed from Apdex ratings
- Change Visually Complete Apdex timings to …

PSREGOV-1191: Remove 97x and CSP Violations from Apdex calculation for RUM apps

---

dashboards/orange/accountmanagement-slas-Orange.json

- Adds max transactions per second for each orange CRI for the product check in
- Updates the OTG tiles to point to OTG (rather than KBV) and removes frontend related tiles (it doesn't have a frontend)

BAU: Update Orange Account Management SLAs board

---

.github/workflows/check.yml
.github/workflows/deploy.yml

Replaces the hardcoded IAM role ARN with a value provided by a repo secret.
This PR should not be merged until the secret has been added to the repo under Security -> Secrets and variables -> Actions -> + New repo secret.
The Action status checks will fail until the PR is merged because Github will not allow a PR to read repo secrets
[PSREGOV-1229]
[PSREGOV-1229]: https://govukverify.atlassian.net/browse/PSREGOV-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREGOV-1229: replace inline GHA IAM role ARNs with repo secret

---

services_anomaly_detection.tf

After the global anomaly detection settings were deployed out, an incident with one of our Suppliers was missed because the settings were too high to have triggered an alert.
This change is introducing Supplier-specific anomaly detection settings so that they can be tailored by each use case, but at the moment this is just reducing the request per minute settings for each Supplier as the global setting is too high.
PSREGOV-1167

Created service specific anomaly settings for Suppliers

---

modules/web_application/main.tf

Following the Dynatrace session last week, this is converting the manual changes they made in the Auth RUM app into IaC and deploying those across the other 10 RUM apps.
The changes consist of three main things:
- XHR naming rule
- Exclusion rule for Google Analytics
- Session and user action properties
PSREGOV-1236

Addition of session and user action properties

---

modules/web_application/main.tf

IDs need to be unique and Dynatrace had already created a few before deleting them and so in theory, the sequence should have started from 2.
To avoid having to add conditionals to both Auth and IPV Core, I'm starting the sequence fresh from 10. 
PSREGOV-1236

Updating unique IDs because of previous usage

---

settings_server_side_service_monitoring.tf

Creation of a new global suppression rule for the invalid session error being received by TSD, approval from both teams and TSD that this can be suppressed has been given.
PSREGOV-1290

Added in new global suppression rule for invalid session

---

dashboards/dev-platform/teams_pipeline_dora_dashboard_cfr.tftpl

- Some dashboards were showing negative Change Failure Rate values for integration environment
- This is due to dashboards not accounting for a test phase in integration
- This is fixed by adding an extra filter to integration and production environments to only account for deploy stage 
metrics
- Added missing formatting 0.00% for CFR across environments tiles
[PSREDEV-387]
[PSREDEV-387]: https://govukverify.atlassian.net/browse/PSREDEV-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREDEV-387: add extra filter to int & prod envs

---

settings_server_side_service_monitoring.tf

Error in the comparison type being used, was using service_type and should be fast_string and switched from EQUALS to CONTAINS
PSREGOV-1416

Error in the comparison type

---

dashboards/orange/check-hmrc-lambda-metrics.json

Check HMRC CRI now has just one lambda managing epoch times the dashboards artifacts have been removed for the removed lambdas i.e.
- get-epoch-time-handler.ts
- current-time-handler.ts
- create-auth-code-handler.ts
Only time-handler is in use now with associated dynatrace tiles
see: dashboard [here](https://bhe21058.live.dynatrace.com/#dashboard;id=041340d9-d6b8-4982-8f5e-e67506c777e9;applyDashboardDefaults=true)
[OJ-2230](https://govukverify.atlassian.net/browse/OJ-2230)
[OJ-2230]: https://govukverify.atlassian.net/browse/OJ-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2230: Removed tiles unneeded handlers

---

CODEOWNERS

Amending codeowners to instead reference the new fog team

Changing to reference the new fog team

---

dashboards/kiwi/bav-cri.json
dashboards/kiwi/bav-lambda-metrics.json
dashboards/kiwi/sqs-metrics.json

- Edit KIWI dashboards
- Previously, filters were hardcoded to show Production data only and the dashboards were missing some data in the non-prod instance
- This PR uses filters so that the data from build to prod can be viewed with the same json file
- `prefix` has also been used (similar to wildcard) to track resources that have environment specific name/AWS' autogenerated strings
- Also addresses other comments from https://govukverify.atlassian.net/browse/IPS-760?focusedCommentId=181080 (fixing broken links and missing data)
[IPS-1212](https://govukverify.atlassian.net/browse/IPS-1212)
[IPS-1212]: https://govukverify.atlassian.net/browse/IPS-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1212: Kiwi dashboards

---

settings_server_side_service_monitoring.tf

Based on the recommendation from Dynatrace, amending the failure detection parameters to use success forcing exceptions instead of ignored exceptions.
PSREGOV-1456

Amending failure parameters based on Dynatrace recommendations

---

dashboards.tf
dashboards/orange/experian-kbv-cri.json
dashboards/orange/experian-kbv-lambda-metrics.json

We now have multiple KBV CRIs and have introduced a naming convention of {third party service} KBV to reduce confusion across the programme. This means that KBV needs to be renamed to Experian KBV.
Renaming both Orange KBV dashboards, files and tiles to include Experian.
[OJ-2795]
[OJ-2795]: https://govukverify.atlassian.net/browse/OJ-2795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2795: Rename Orange KBV to include Experian

---

dashboards/orange/experian-kbv-lambda-metrics.json

Added the following to kbv lambda metrics:
[OJ-2840]
[OJ-2840]: https://govukverify.atlassian.net/browse/OJ-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2840: Add graph for SOAP token latency

---

dashboards/encrypted-vc-storage/encrypted_vc_storage_dashboard.json

[ATB-1862 | Add Token Validation Failed Metric to Authoriser Issues panel
](https://govukverify.atlassian.net/browse/ATB-1862)
Added the metric ` cloud.aws.vcstorage.tokeN_VALIDATION_FAILEDByAccountIdRegionservice:count` to Authorizer Issues tile. 
Tested in Dev by running the pipeline:

ATB-1862 | Add Token Validation Failed Metric to Authoriser Issues panel

---

dashboards/authentication/account-interventions-integration.json
dashboards/authentication/account-interventions-prod.json
dashboards/authentication/account-interventions-staging.json
dashboards/authentication/di-auth-notify-delivery-receipts/di-auth-notify-delivery-receipts.json.tpl
dashboards/authentication/di-auth-notify-delivery-receipts/main.tf
dashboards/authentication/di-auth-notify-delivery-receipts/provider.tf
dashboards/authentication/di-auth-notify-delivery-receipts/variables.tf

Adds a new dashboard for authentication (notify metrics). This dashboard is being ported over from an [existing grafana dashboard](https://g-8e26091ad7.grafana-workspace.eu-west-2.amazonaws.com/d/ufjJdaR4z/authentication-notify-metrics?orgId=1).
I have tested this out by pasting the json into the dynatrace dashboard that I've been playing around with to make this PR.
AUT-3879

Aut 3879/add auth notify dashboard

---

dashboards.tf
dashboards/authentication/di-auth-notify-delivery-receipts/di-auth-notify-delivery-receipts.json.tpl

A couple of things I missed from https://github.com/govuk-one-login/observability-configuration/pull/351
* Adding the new dashboards to dashboards.tf, to ensure they deploy
* Adding an environment filter to ensure that the two envs in non-prod (staging and integration) are treated separately
I have also tested this out by pasting the json into the dynatrace dashboard that I've been playing around with to make this PR.
AUT-3879

Aut 3879/add notify dashboards

---

dashboards.tf

We don't currently have the notify callback wired up in envs other than production so these dashboards are showing no data. Removing so it's not misleading. I'm not removing the parameterisation in the template / terraform for now in case we change this in future
Last PR on this hopefully!
AUT-3879

AUT-3879: Remove non prod dashboards for auth notify

---

services_anomaly_detection.tf

Following consultation with the TSD and the Dev team, this service produces weekly alerts that are non-actionable and these changes are to amend the alerting thresholds specifically for this service and in particular, the response time degradation alerting.
PSREGOV-1700

Added service alerting configuration for the onboarding product page

---

modules/web_application/injection_rules.tf
modules/web_application/variables.tf
web_applications.tf

Existing issue with the TF state file not containing this config, and each time a deployment occurs it deletes the manually created config in the UI.
This is one of two PRs to sort out the state file and UI sync issue, this will remove all the config and then the second will add the config back in and hopefully get it deployed out.
PSREGOV-1849

Removing injection rules to tidy up state file

---

dashboards/orange/experian-kbv-cri.json
dashboards/orange/experian-kbv-lambda-metrics.json

Minor updates to Experian KBV dashboards as `execution_duration` and `transition_id` dimensions will no longer exist when the following is merged: https://github.com/govuk-one-login/ipv-cri-kbv-api/pull/458 
- [OJ-2845](https://govukverify.atlassian.net/browse/OJ-2845)
[OJ-2845]: https://govukverify.atlassian.net/browse/OJ-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2845: Remove dimensions from duration metrics

---

dashboards-cloudfront.tf

Remove the Auth inactive CloudFront Monitor dashboard , This dashboard was created for CloudFront Migration not is use so can be removed 
[N/A]
- [ yes] Is my change backwards compatible? Please include evidence
- [no ] I have tested this and added output to Jira Comment:

BAU: Remove the Auth inactive CloudFront Monitor dashboard

---

dashboards/spot/key-rotation-dashboard.json

Added the SPOT Key Management status to the SPOT Key Rotations Dashboard so that it presents the current state of the SPOT Key Rotation.
[SPT-1256](https://govukverify.atlassian.net/browse/SPT-1256)
[SPT-1256]: https://govukverify.atlassian.net/browse/SPT-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SPT-1256: Dynatrace SPOT-KM Step Function Metrics

---

dashboards.tf

Added `key-rotations-dashboard.json` to dashboards Terraform configuration as module `spot_key_rotations_dashboard`. So that the SPOT Key Rotations Dashboard is deployed.
[SPT-1256](https://govukverify.atlassian.net/browse/SPT-1256)
[SPT-1256]: https://govukverify.atlassian.net/browse/SPT-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SPT-1256: Added key-rotations-dashboard to TF

---

modules/web_application/main.tf
modules/web_application/variables.tf
web_applications.tf

Due to increased Dynatrace costs and RUM being the second most expensive feature, this work is to implement customisation for the cost_control_user_session_percentage attribute and this has currently been set from the original 100% to 50% across the board.
If needed in the future, this config allows the value to be amended per RUM application.
PSREGOV-2099

Added in config to customise user session percentage

---

modules/web_application/injection_rules.tf
modules/web_application/main.tf
modules/web_application/variables.tf
web_applications.tf

Removal of the old RUM custom injection rules config as it was conflicting with the `dynatrace_web_application` javascript injection rules attribute that was missing, on the premise that the aforementioned resource should have worked.
This new config defines an injection rule against each RUM application, two are set to not automatically inject while the rest are set to automatic injection.
PSREGOV-1233

RUM updated for custom injection rules

---

modules/web_application/main.tf

Who knew that a non-required enabled attribute is actually required to enable the custom injection rules...
PSREGOV-1233

Added the enabled boolean to injection rules

---

settings_server_side_service_monitoring.tf

These parameters/rules work on a first-match basis and when we had four different ones, the bottom rule wasn't being picked up and so Problems in Dynatrace were still containing these errors.
The suggestion from Dynatrace was to combine these into one, so that all conditions were met on the first match.
PSREGOV-2264

Failure detection parameters update

---

.github/workflows/check.yml

Prevent workflow runs on Dependabot pull requests by adding `branches-ignore` filter. This avoids potential failures due to missing secret access for automated dependency updates.
[PSREGOV-2132](https://govukverify.atlassian.net/browse/PSREGOV-2312)
[PSREGOV-2132]: https://govukverify.atlassian.net/browse/PSREGOV-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Exclude Dependabot PRs from workflow execution

---

.gitignore
dashboards/team-idc-app.json

- **Updated with tiles for TEAM Policy processing resources.**
- **Added .DS_Store to gitignore.**
@rorysedgwick confirmed he's happy with the new dashboard tiles so this will update the IaC config.
[PSREGOV-2080](https://govukverify.atlassian.net/browse/PSREGOV-2080)
[PSREGOV-2080]: https://govukverify.atlassian.net/browse/PSREGOV-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREGOV 2080 - Update Dynatrace dashboard to reflect policy processing pipeline

---

dashboards.tf
dashboards/id-check/standard-metrics.json

Add count parameter to only deploy ID Check dashboards to Prod to prevent breaking TF NonProdDeployments.
Remove the hidden metrics from the dashboard.
[DCMAW-12567]
[DCMAW-12567]: https://govukverify.atlassian.net/browse/DCMAW-12567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DCMAW-12567] Add count parameter to only deploy ID Check dashboards to Prod

---

dashboards.tf
dashboards/spot/cimit-performance-metrics.json
dashboards/spot/spot-performance-metrics.json

- Add the `spot-performance-metrics` dashboard
- Add the `cimit-performance-metrics` dashboard
- Update Terraform to deploy above dashboards
[SPT-1395]
[SPT-1395]: https://govukverify.atlassian.net/browse/SPT-1395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SPT-1395: Add new SPOT & CIMIT dashboards

---

.github/workflows/check.yml

Fix: Removed `main` from `push` to allow Dependabot branch exclusion. 
[[PSREGOV-2312]](https://govukverify.atlassian.net/browse/PSREGOV-2312)
[PSREGOV-2312]: https://govukverify.atlassian.net/browse/PSREGOV-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent Dependabot workflow runs on push and PR events.

---

dashboards/id-check/standard-metrics.json

Update lambda concurrency table to use max value instead of average
[DCMAW-12652]
[DCMAW-12652]: https://govukverify.atlassian.net/browse/DCMAW-12652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DCMAW-12652] Update lambda concurrency to use max value instead of average

---

.github/workflows/check.yml
.github/workflows/deploy.yml

Skip checks on Dependabot PRs to avoid secret access failures during automated dependency updates.
Fix: Prevent workflow execution on Dependabot PRs and subsequent deployment triggers from Dependabot merges.
[[PSREGOV-2312]](https://govukverify.atlassian.net/browse/PSREGOV-2312)
[PSREGOV-2312]: https://govukverify.atlassian.net/browse/PSREGOV-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Skip checks on Dependabot PRs using conditional job execution.

---

settings_team_anomaly_detection.tf

An alert for a step function was being raised and I realised it should be changed from static to auto adaptive threshold.
[PSREGOV-2251](https://govukverify.atlassian.net/browse/PSREGOV-2251)
[PSREGOV-2251]: https://govukverify.atlassian.net/browse/PSREGOV-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changed step function alert to auto adaptive threshold from static threshold

---

settings_team_anomaly_detection.tf

- Updated alert description format
- Removed dynamodb capacity alerts as these don't seem to be useful
[PSREGOV-2250](https://govukverify.atlassian.net/browse/PSREGOV-2250)
[PSREGOV-2250]: https://govukverify.atlassian.net/browse/PSREGOV-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSREGOV 2250 - Remove DynamoDB capacity alerts

---

documents.tf
documents/core/apigw-metrics.json
documents/fpad/fpad-infrastructure.json
modules/documents/main.tf
modules/documents/provider.tf
modules/documents/variables.tf

Creation of a new documents module to cater for dashboards created in "new" Dynatrace, also combined two dashboards created by IPV Core and FPAD which were originally raised as separate PRs, but put on hold until this module was created.
PSREGOV-2259

Addition of documents module

---

dashboards/orange/check-hmrc-lambda-metrics.json

With the conversion of the NINo Check logic from a step function to a Lambda function, we are finding that the metrics are now pushed with a different 'service' dimension. This change adds the new dimension to the 'OR' statements in our HMRC API graphs to ensure continuity of metrics across the transition.
- OJ-3197

OJ-3197 - Include metrics pushed by the NinoCheckFunction in HMRC latency graphs

---

documents/fpad/fpad-infrastructure.json

[FPAD-5339]
[FPAD-5339]: https://govukverify.atlassian.net/browse/FPAD-5339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FPAD-5339: Show number of messages for each queue in Dynatrace SQS Widgets

---

dashboards.tf
dashboards/mobile-platform/sts/sts-behaviours.json

DCMAW-12373 - Added terraform resource for STS and MP dashboards
[DCMAW-12373]
[DCMAW-12373]: https://govukverify.atlassian.net/browse/DCMAW-12373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DCMAW-12373 - Added terraform resource for STS and MP dashboards

---

dashboards/mobile-platform/mobile-platform.json
dashboards/mobile-platform/sts.json

Updated dashboards thresholds for API GW saturation
[DCMAW-14167]
[DCMAW-14167]: https://govukverify.atlassian.net/browse/DCMAW-14167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DCMAW-14167 - Updated dashboards thresholds for API GW saturation

---

dashboards/orange/address-lambda-metrics.json
dashboards/orange/check-hmrc-lambda-metrics.json
dashboards/orange/experian-kbv-lambda-metrics.json

Added JWT Verification Failure tile to Orange CRI lambda dashboards.
[OJ-3249]
[OJ-3249]: https://govukverify.atlassian.net/browse/OJ-3249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3249: Add JWT Verification Failure tile

---

dashboards/id-check/async-backend-completion-rate.json
dashboards/id-check/dcmaw-backend-completion-rate.json

Add timefilter to journey completion over 7 days tile for dmcaw and async
[DCMAW-14901](https://govukverify.atlassian.net/browse/DCMAW-14901)
[DCMAW-14901]: https://govukverify.atlassian.net/browse/DCMAW-14901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DCMAW-14901: add timefilter to journey completion over time tile

---

dashboards/spot/spot-performance-metrics.json

Updated SPOT Key Rotations dashboard as due to a recent change to AWS Powertools new dimensions have now been added changing the name of the metric selector. The updated selectors combine the old and new metrics to create a composite value.
This updates the tiles for Spot performance metrics for sections Signed Responses Sent/Profiles Issued/Level of Confidence Issued/ Profiles Issued over time/Conditional Profiles Allowed
[SPT-1534: SPOT: Metrics Powertools Java Upgrade](https://govukverify.atlassian.net/browse/SPT-1534)

SPT-1534:Dynatrace dashboard changes

---

settings_anomaly_detection.tf

Updated the WAF blocked requests alert config to ensure that it only fires when the value is 10x greater than the norm
PSREGOV-2947

Updated WAF blocked requests alert config

---

dashboards.tf
dashboards/orchestration/general_non_prod.json
dashboards/orchestration/general_prod.json

We'd like some dashboards for generic orch metrics (prod and non prod).
[ATO-1943]
[ATO-1943]: https://govukverify.atlassian.net/browse/ATO-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATO-1943: Create generic orchestration dashboards

---

dashboards/orange/experian-kbv-cri.json

- We have tweaked the name of a new step function being monitored; this PR makes that change. Backwards compatibility is not necessary as the step function is new and no-one except team Orange is checking it at the moment.
- We have also updated the metric selectors for the same plot to ensure that it sums across accounts rather than creating separate lines for each account.
Here is what the new plot looks like in a test dashboard:
- OJ-3294

OJ-3294 - Update step function name; merge accounts & regions

---

dashboards/orange/experian-kbv-cri.json

Minor fixes for the KBV certificate expiry dashboard:
- Display sum, not count, on the big number metric tiles
- Minor legibility improvements to the step function execution plot legend
- [OJ-3294](https://govukverify.atlassian.net/browse/OJ-3294)
[OJ-3294]: https://govukverify.atlassian.net/browse/OJ-3294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3294 - Use sum instead of count; correct execution plot legend

---

dashboards/orchestration/general_non_prod.json
dashboards/orchestration/general_prod.json

Context: `clientName` was previously added as a dimension to the `successfulTokenIssued` metric and the orch dashboards updated accordingly. However, changing the metric broke other dashboards so it was reverted.
- Revert orch dashboards to using the original metric for `successfulTokenIssued`, without the `clientName` dimension.
- Remove the graph showing tokens issued by RP from the orch dashboards, because this is already available in the [RP Dashboard](https://bhe21058.apps.dynatrace.com/ui/apps/dynatrace.classic.dashboards/#dashboard;gtf=-6h;gf=all;id=7ebbeb31-abe0-4dc7-a07b-46ea127c65fd)
[ATO-1946](https://govukverify.atlassian.net/browse/ATO-1946)
[ATO-1946]: https://govukverify.atlassian.net/browse/ATO-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

ATO-1946 Fix tokens issued graphs on orch dashboards

---

dashboards/orchestration/general_non_prod.json
dashboards/orchestration/general_prod.json

- Update the token metric to include the clientName dimension
- Add a chart of tokens issued by client name
[ATO-1946](https://govukverify.atlassian.net/browse/ATO-1946)
[ATO-1946]: https://govukverify.atlassian.net/browse/ATO-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATO-1946: Update token metric and add token chart

---

dashboards/id-check/dcmaw-backend-lambda.json

[DCMAW-15694]
Change: the AWS custom metric dimensions have changed and therefore metrics are no longer available. This updates queries to use the latest dimension from AWS.
The diff is larger than I expected. From some spot checks, it looks like the majority of the diff is due to reordering of keys in the JSON. Process to produce this:
1. Clone dashboard
2. Export JSON to confirm the diff only contains metadata changes ✅ 
3. Click-ops changes to Dynatrace tiles - changes to a number of tiles to update the query used
4. Export JSON
5. Push changes using exported JSON
I've reviewed the click-opsed dashboard vs the original dashboard in Dynatrace - the untouched tiles look the same. The changed tiles are pulling through metrics using the latest metric dimensions.
[DCMAW-15694]: …

DCMAW-15694: Fix DCMAW lambda dashboard to use latest metric dimensions
