govuk-one-login/observability-configuration

env_settings.tf
add instrumentation key for oneagent_features
[OBS-185]
[OBS-185]: https://govukverify.atlassian.net/browse/OBS-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-185 add instrumentation key for oneagent_features

env_settings.tf
fix terraform fmt for env_settings.tf
[OBS-185]
[OBS-185]: https://govukverify.atlassian.net/browse/OBS-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix terraform fmt for env_settings.tf

service_detection.tf
add service detection for YOTI
[OBS-161]
[OBS-161]: https://govukverify.atlassian.net/browse/OBS-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> f/OBS-161 add service detection for YOTI

service_detection.tf
Add Ordnance Survey to service detection
[OBS-153]
[OBS-153]: https://govukverify.atlassian.net/browse/OBS-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-153 add Ordnance Survey to service detection

service_detection.tf
[OBS-186]
[OBS-186]: https://govukverify.atlassian.net/browse/OBS-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated with External Web Requests

service_detection.tf
[OBS-186]
[OBS-186]: https://govukverify.atlassian.net/browse/OBS-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated resource names

dashboards.tf, service_detection.tf
fix broken pipeline
[OBS-186]
[OBS-186]: https://govukverify.atlassian.net/browse/OBS-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-186 fix broken pipeline

alerting_profiles.tf, data.tf, problem_notifications.tf
IaC for alerting profiles and problem notifications
[OBS-199]
[OBS-199]: https://govukverify.atlassian.net/browse/OBS-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IaC for Dynatrace alerting config

service_detection.tf
add post office to service detection
[OBS-154]
[OBS-154]: https://govukverify.atlassian.net/browse/OBS-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-154 add post office to service detection

dashboards/dora_metrics_dashboard.json
[OBS-58]
[OBS-58]: https://govukverify.atlassian.net/browse/OBS-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removing ID

dashboards/signin-signup.json
Deploying a different journey to production has resulted in a change to the emitted metrics. Update the  sign in/up dashboard to show the correct docapp figures
ATO-255
=> ATO-255: Update docapp journeys graph

dashboards/signin-signup.json
Update frontchannel logout graph on sign-in-up dashboard to reflect added dimension
=> Update metric for frontchannel logout

settings_ownership.tf
[OBS-226]
[OBS-226]: https://govukverify.atlassian.net/browse/OBS-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IaC for ownership config settings

settings_business_analytics.tf, settings_ownership.tf
[OBS-232]
[OBS-232]: https://govukverify.atlassian.net/browse/OBS-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IaC for Business Analytics Settings

settings_business_analytics.tf
[OBS-232]
[OBS-232]: https://govukverify.atlassian.net/browse/OBS-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating as failed checks

settings_web_mobile_monitoring.tf
IaC for Web and mobile monitoring config settings in Dynatrace
[OBS-228]
[OBS-228]: https://govukverify.atlassian.net/browse/OBS-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-228 - Add web and mobile monitoring config settings

settings_processes_containers.tf
IaC for Processes and containers config settings in Dynatrace
[OBS-227]
[OBS-227]: https://govukverify.atlassian.net/browse/OBS-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-227 add processes and containers config settings in Dynatrace

settings_processes_containers.tf
fix enable auto deep monitoring
[OBS-227]
[OBS-227]: https://govukverify.atlassian.net/browse/OBS-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OBS-227 fix enable auto deep monitoring

slos.tf
Variety of changes applied to all SLOs with the addition of new Service-level SLOs
[OBS-254]
[OBS-254]: https://govukverify.atlassian.net/browse/OBS-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Variety of changes applied to all SLOs

settings_updates_config
[OBS-237]
[OBS-237]: https://govukverify.atlassian.net/browse/OBS-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> new settings update config

dashboards.tf
=> plat-3143-1 Configuring dynatrace dora metrics dashboards 

dashboards/dev-platform/dora_demo_sam_app_dashboard.json, dashboards/dev-platform/test_team_1_dashboard.json, dashboards/dev-platform/test_team_2_dashboard.json
[PLAT-3143]
[PLAT-3143]: https://govukverify.atlassian.net/browse/PLAT-3143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removing ID we added to the new boards

dashboards/dev-platform/test_team_1_dashboard.json
[PLAT-3783]
[PLAT-3783]: https://govukverify.atlassian.net/browse/PLAT-3783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> plat-3783 Added example team json template

.github/workflows/check.yml
Update Github actions to latest version
[OBS-XXX]
=> Update Github actions to latest version

dashboards.tf, dashboards/dev-platform/TEMPLATE_dashboard.json
adding dashboard using variables for teams names and sharing
[PLAT-3783]
[PLAT-3783]: https://govukverify.atlassian.net/browse/PLAT-3783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding dashboard using variables for teams names and sharing

dashboards.tf
adding dashboard using variables for teams names
[OBS-XXX]
=> adding dashboard using variables for teams names

dashboards.tf, dashboards/dev-platform/TEMPLATE_dashboard.json
Adding dashboard using variables for teams names and sam stack name
[OBS-XXX]
=> Adding dashboard using variables for teams names and sam stack name

dashboards/dev-platform/TEMPLATE_dashboard.json
=> Update TEMPLATE_dashboard.json to include team name in header

dashboards.tf, dashboards/dev-platform/TEMPLATE_dashboard.json
adding dashboard with real team names
[OBS-XXX]
=> adding dashboard with real team names

dashboards/dev-platform/TEMPLATE_dashboard.json
dora dashboards - adding sparklines and trend lines
[OBS-XXX]
=> dora dashboards - adding sparklines and trend lines

failure_detection.tf
=> Include 4xx in client side errors :eyes:

.github/dependabot.yml
=> Create dependabot.yml for github actions

slos.tf
MZ names were changed, but the SLOs rely on these to work and have been failing since. This change is to correct the MZ names against the SLOs.
=> Update of MZ names since AWS was prefixed

dashboards/dev-platform/TEMPLATE_dashboard.json
=> remove team name from dashboard

README.md, dashboards.tf, dashboards/txma/txma_shared_signals_dashboard.json
Adding in TxMA's Shared Signals Dashboard to Prod Instance 
[[TT2-1544](https://govukverify.atlassian.net/browse/TT2-1544)] 
[TT2-1544]: https://govukverify.atlassian.net/browse/TT2-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TT2-1544 | Add TxMA Shared Signals Dashboard

dashboards.tf, dashboards/account-interventions-service/account_interventions_service_dashboard.json
ATB-1534 | Add Account Interventions Service Dynatrace Dashboard to Prod Instance
[OBS-XXX]
=> ATB-1534 | Add Account Interventions Service Dynatrace Dashboard to Prod 

dashboards.tf, dashboards/dev-platform/TEMPLATE2_dashboard.json
adding 2nd dashboard
[OBS-XXX]
=> adding 2nd dashboard

dashboards/dev-platform/TEMPLATE2_dashboard.json
fixing missing name as variable
[OBS-XXX]
=> fixing missing name as variable

dashboards/dev-platform/TEMPLATE_dashboard.json
=> adding more dora dashboards

dashboards-cloudfront.tf, dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json
adding cloudfront dashboards
[OBS-XXX]
=> adding cloudfront dashboards

dashboards-cloudfront.tf, dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json
Cloudfront dashboards - more
[OBS-XXX]
=> Cloudfront dashboards - more

dashboards.tf, dashboards/orchestration/account-interventions-integration.json, dashboards/orchestration/account-interventions-prod.json, dashboards/orchestration/account-interventions-staging.json
Add a dashboard to monitor Orch calls to AIS. Useful for monitoring performance and stability during rollout period.
=> Add dashboard for Orch calls to AIS

settings_service_mzs.tf
Add rules for Synthetics to MZs, allowing users to create Synthetics.
=> Add rules for Synthetics to MZs

slos.tf
With the update of the entityId for the Experian service, the SLO needs updating with the new ID.
[PSREOBS-161]
[PSREOBS-161]: https://govukverify.atlassian.net/browse/PSREOBS-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated entityId for Experian

dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json
dashboards - new cloudfront and ALB
[OBS-XXX]
=> dashboards - new cloudfront and ALB

dashboards.tf, dashboards/dap/data-and-analytics-prod.json
=> added dap dashboard

dashboards/dev-platform/TEMPLATE2_dashboard.json, dashboards/dev-platform/TEMPLATE3_dashboard.json, dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json, dashboards/dev-platform/TEMPLATE_dashboard.json
more DORA dashboards
[OBS-XXX]
=> more DORA dashboards

slos.tf
Following the creation of additional service detection rules, these Suppliers can now be added as SLOs
PSREOBS-37
=> Added additional SLOs for new Suppliers

slos.tf
Copy/paste error, renaming metric_name for the new SLOs
PSREOBS-37
=> Updated metric_name, copy and paste error

settings_web_mobile_monitoring.tf, web_applications.tf
=> Enable RUM for all staging domains

dashboards/slos.json
Updated SLO dashboard to include new Supplier SLOs
PSREOBS-37
=> Updated SLO dashboard with new Supplier SLOs

web_applications.tf
=> Add applications for each subdomains (list inexhaustive, add to later!)

web_applications.tf
=> Fix if statement being the wrong way around

dashboards-dora.tf, dashboards/dev-platform/TEMPLATE3_dashboard.json
DevPlatform demo sam apps dashboard
Additionally, a title field on template3 dashboard
[PLAT-4340]
[PLAT-4340]: https://govukverify.atlassian.net/browse/PLAT-4340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DevPlatform demo sam apps dashboard

dashboards/dev-platform/TEMPLATE2_dashboard.json, dashboards/dev-platform/TEMPLATE3_dashboard.json, dashboards/dev-platform/TEMPLATE_dashboard.json
remove limit from dora dashboards
[OBS-XXX]
=> remove limit from dora dashboards

dashboards/dev-platform/TEMPLATE1_dashboard.json, dashboards/dev-platform/TEMPLATE2_dashboard.json, dashboards/dev-platform/TEMPLATE3_dashboard.json
Remove limit() from templates
[PLAT-4353]
[PLAT-4353]: https://govukverify.atlassian.net/browse/PLAT-4353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-4353 - Remove limit() from templates

modules/web_application/main.tf, modules/web_application/variables.tf, web_applications.tf
Disable gathering of RUM data in staging while we work on data protection issues. :)
=> Disable RUM in staging

dashboards.tf, dashboards/service-dashboard.json
Addition of initial creation of the Service Dashboard for Production Dynatrace
PSREOBS-161
=> Addition of top-level Service Dashboard

dashboards.tf, dashboards/orange/dashboard-builder/main.tf, dashboards/orange/dashboard-builder/templates/otg-cri.tpl.json, dashboards/orange/dashboard-builder/templates/otg-lambda-metrics.tpl.json, dashboards/orange/dashboard-builder/variables.tf
added orange dashboards for OTG CRI.
[OJ-2496](https://govukverify.atlassian.net/browse/OJ-2496)
[OJ-2496]: https://govukverify.atlassian.net/browse/OJ-2496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added orange dashboards for OTG CRI.

dashboards/capacity/application-performance-review.json
[LS-2037]
[LS-2037]: https://govukverify.atlassian.net/browse/LS-2037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2037 Updated Capacity/performance dashboard to use non ext: metrics

slos.tf
Update slos.tf - cloud.aws.apigateway
[PSREDP-632]
[PSREDP-632]: https://govukverify.atlassian.net/browse/PSREDP-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update slos.tf - cloud.aws.apigateway

dashboards/capacity/application-performance-review.json
[LS-2042]
- [] Documentation added (link) Comment:
[LS-2042]: https://govukverify.atlassian.net/browse/LS-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2042 Updated Dashboards to show BackendAPI Errors

dashboards/lime/passport-cri.json
Updated passport-cri.json
The existing dashboard was cloned, in order to make the required changes. These changes were checked in order to match the current dashboards data. This JSON data was then exported and imported into this codebase.
[[PSREDP-632](https://govukverify.atlassian.net/browse/PSREDP-632)] 
[PSREDP-632]: https://govukverify.atlassian.net/browse/PSREDP-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update passport-cri.json dashboard

dashboards/capacity/application-performance-review.json
[LS-2042]
[LS-2042]: https://govukverify.atlassian.net/browse/LS-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2042 Fixed errors by switching to sum

dashboards/core/services.json
Updated core/services.json
The existing dashboard was cloned, in order to make the required changes. These changes were checked in order to match the current dashboards data. This JSON data was then exported and imported into this codebase.
[[PSREDP-632](https://govukverify.atlassian.net/browse/PSREDP-632)]
[PSREDP-632]: https://govukverify.atlassian.net/browse/PSREDP-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Core services dashboard

dashboards/lime/apigw-metrics.json
Updated lime apigw-metrics.json file.
The existing dashboard was cloned, in order to make the required changes. These changes were checked in order to match the current dashboards data. This JSON data was then exported and imported into this codebase.
[[PSREDP-632](https://govukverify.atlassian.net/browse/PSREDP-632)]
[PSREDP-632]: https://govukverify.atlassian.net/browse/PSREDP-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update lime API Gateway metrics dashboard

dashboards/capacity/application-performance-review.json
[LS-2043]
[LS-2043]: https://govukverify.atlassian.net/browse/LS-2043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2043 Added two CloudFront monitors

dashboards/dev-platform/TEMPLATE_cloudfront_dashboard.json
Update TEMPLATE_cloudfront_dashboard.json - remove INT environment
[OBS-XXX]
=> Update TEMPLATE_cloudfront_dashboard.json - remove INT environment

dashboards/dev-platform/TEMPLATE1_dashboard.json
Refactoring dev-platform dashboards queries
[PSREDEV-394]
[PSREDEV-394]: https://govukverify.atlassian.net/browse/PSREDEV-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSREDEV-394 - Refactoring dev-platform dashboards queries

dashboards/dev-platform/TEMPLATE1_dashboard.json, dashboards/dev-platform/TEMPLATE2_dashboard.json, dashboards/dev-platform/TEMPLATE3_dashboard.json
Pipeline DORA dashboards how-to-use header, tag and all management zone filter on tiles
[PSREDEV-367]
[PSREDEV-367]: https://govukverify.atlassian.net/browse/PSREDEV-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSREDEV-367 - Pipeline DORA dashboards headers, tags and all management zone filter

dashboards/dev-platform/TEMPLATE2_dashboard.json, dashboards/dev-platform/TEMPLATE3_dashboard.json
Remove or() from devplatform dora dashboards. 
[PSREDEV-394]
[PSREDEV-394]: https://govukverify.atlassian.net/browse/PSREDEV-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSREDEV-394 - Remove or() from devplatform dora dashboards

dashboards-cloudfront.tf
[DCMAW-8813]
[DCMAW-8813]: https://govukverify.atlassian.net/browse/DCMAW-8813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-8813: Added ID Check to CloudFront Dynatrace Dashboard

dashboards/txma/txma-shared-signals-integration.json, dashboards/txma/txma-shared-signals-production.json
=> Moving Shared signals board metrics to use cloud.aws

get-accounts.py
Adds accounts under the production tools OU to list of production accounts.
[PSREGOV-308]
[PSREGOV-308]: https://govukverify.atlassian.net/browse/PSREGOV-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add production tools OU to production account config list

dashboards-cloudfront.tf
[LIME-1165]
[LIME-1165]: https://govukverify.atlassian.net/browse/LIME-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1165 Creating Lime Dynatrace Dashboards for cloudfront

dashboards.tf, dashboards/txma/txma-deployment-production.json
=> TT2-1833: Adding TxMA deployment stats dashboard

dashboards.tf, dashboards/capacity/critical-conformance.json
Adds a dashboard showing compliance with the Critical Conformance Packs across the org.
[LS-2134]
[LS-2134]: https://govukverify.atlassian.net/browse/LS-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2134 Created Critical Conformance Dashboards

dashboards.tf, dashboards/capacity/critical-conformance.json, dashboards/capacity/pab-conformance.json
This splits the conformance dashboards onto two dashboards split by conformance pack.
[LS-2134]
[LS-2134]: https://govukverify.atlassian.net/browse/LS-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2134 Conformance split

dashboards.tf, dashboards/core/apigw-metrics.json, dashboards/core/lambda.json, dashboards/core/services.json, dashboards/core/sqs-metrics.json, dashboards/core/traffic.json
- Updated the existing Core-Services and Lambda-Metrics dashboards
- Add new dashboards to monitor API Gateway, Traffic and SQS metrics
[IPS-800]
[IPS-800]: https://govukverify.atlassian.net/browse/IPS-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-800: Update existing Core dashboards and add additional

dashboards.tf, dashboards/kiwi/apigw-metrics.json, dashboards/kiwi/bav-cri.json, dashboards/kiwi/bav-lambda-metrics.json, dashboards/kiwi/cic-cri.json, dashboards/kiwi/cic-lambda-metrics.json, dashboards/kiwi/ecs-metrics.json, dashboards/kiwi/f2f-cri.json, dashboards/kiwi/ipr-lambda-metrics.json, dashboards/kiwi/services.json, dashboards/kiwi/sqs-metrics.json, dashboards/kiwi/traffic-metrics.json
- Create new dashboards for KIWI BAV CRI
- Update the existing F2F, CIC and IPR with metric streams
[IPS-760]
[IPS-760]: https://govukverify.atlassian.net/browse/IPS-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-760: Add BAV CRI dashboards and update existing KIWI dashboards

dashboards/scaling/ecs_scaling/site.tf
Updated site.tf to set same provider as main.
[LS-2196]
[LS-2196]: https://govukverify.atlassian.net/browse/LS-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2196 Upgraded dynatrace version

dashboards.tf
I'd put the clustername instead of the service name in the template.
[LS-2196]
[LS-2196]: https://govukverify.atlassian.net/browse/LS-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LS-2196 Fixed ref to ClusterName

dashboards.tf, dashboards/id-check/standard-metrics.json
Add Standard Metrics dashboard for ID Check team and update `dashboards.tf`
[DCMAW-9107](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/438?label=Platform&selectedIssue=DCMAW-9107)
[DCMAW-9107]: https://govukverify.atlassian.net/browse/DCMAW-9107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-9107] Add Standard Metrics dashboard for ID Check

dashboards/capacity/Auth-application-performance.json
BAU: Update Auth Non prod Dashboard --This is non prod only Dashboard 
N?A
- [Yes ] Is my change backwards compatible? Please include evidence
- [ No ] I have tested this and added output to Jira Comment: will be tested in Non Prod Dashboard
=> BAU: Update Auth Non prod Dashboard

dashboards/team-idc-app.json
=> Renamed dashboard

dashboards.tf, dashboards/orchestration/oidc-api-gateway-statistics.json
Migrating Grafana dashboards over to dynatrace - OIDC api gateway statistics dashboard
=> ATO-628: add orch oidc api gateway statistics dashboard

dashboards.tf, dashboards/orchestration/dcmaw-journeys.json
Migrating Grafana dashboards over to dynatrace - DCMAW to orchestration journeys dashboard
=> ATO-628: add orchestration dcmaw journey dashboard

dashboards.tf, dashboards/orchestration/authentication.json
Migrating Grafana dashboards over to dynatrace - Authentication dashboard
=> ATO-628: add orchestration authentication dashboard

dashboards.tf, dashboards/id-check/deployment-metrics.json, dashboards/id-check/service-quotas.json
Add deployment metrics and service quota dashboards to Production environment.
[DCMAW-9148](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/438?label=Platform&selectedIssue=DCMAW-9148)
[DCMAW-9147](https://govukverify.atlassian.net/jira/software/c/projects/DCMAW/boards/438?label=Platform&selectedIssue=DCMAW-9147)
[DCMAW-9148]: https://govukverify.atlassian.net/browse/DCMAW-9148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCMAW-9147]: https://govukverify.atlassian.net/browse/DCMAW-9147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-9148] Add deployment metrics and service quota dashboards to prod env

dashboards.tf, dashboards/authentication/di-auth-ticf/di-auth-ticf.json.tpl, dashboards/authentication/di-auth-ticf/main.tf, dashboards/authentication/di-auth-ticf/site.tf, dashboards/authentication/di-auth-ticf/variables.tf
Add dashboards for prod, integration and staging for authentication's calls to the TICF CRI.
AUT-2498
=> AUT-2498: Add auth dashboards for ticf integration

dashboards/signin-signup.json
Removes trends from auth dashboards, as communicating potentially incorrect data.
=> Remove trends from GOV.UK Sign In/Up Dashboard

dashboards.tf, dashboards/encrypted-vc-storage/encrypted_vc_storage_dashboard.json
ATB-1725 | Add Encrypted VC Storage Dashboard to Prod Instance. 
[OBS-XXX]
=> ATB-1725 | Add Encrypted VC Storage Dashboard to Prod Instance 

dashboards.tf, dashboards/mobile-platform/sts/deployments-prod.json, dashboards/mobile-platform/sts/lambdas-prod.json, dashboards/mobile-platform/sts/service-quotas-prod.json, dashboards/mobile-platform/sts/standard-metrics-prod.json, dashboards/mobile-platform/sts/tps-prod.json
This PR creates a set of STS dashboards to be deployed in Production Dynatrace.
These dashboards have been manually created in Prod Dynatrace, and will be manually deleted before merge (to allow Terraform to deploy them without issue).
[DCMAW-8896]
[DCMAW-8896]: https://govukverify.atlassian.net/browse/DCMAW-8896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-8896: STS Prod dashboards

dashboards/service-health-overview.json
=> Updates to Service Overview dashboard

modules/web_application/main.tf, modules/web_application/variables.tf, web_applications.tf
=> Add names to each One Login subdomain

web_applications.tf
Adding the config required for enabling Real User Monitoring (RUM) in the Integration and Production environments
https://govukverify.atlassian.net/browse/PSREGOV-503
=> Addition of Integration and Production RUM config

dashboards.tf, dashboards/service-health-overview.json
-Updated the overview dashboard to include a new RP that went live
-Updated the SLO dashboard module
PSREGOV-833
=> Updated overview dashboard with new RPs

dashboards.tf, dashboards/orange/orange-check-hmrc-step-function.json
[OJ-2497]
[OJ-2497]: https://govukverify.atlassian.net/browse/OJ-2497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2497: Adds NINo step functions dashboard

dashboards/orchestration/authentication.json, dashboards/orchestration/dcmaw-journeys.json, dashboards/orchestration/oidc-api-gateway-statistics.json
Updating current Orchestration graphs with text descriptions
=> ATO-706: add text for orch dashboards to give TSD context

dashboards/encrypted-vc-storage/encrypted_vc_storage_dashboard.json
Revamped the EVCS dashboard
[ATB-1805]()
[ATB-1805]: https://govukverify.atlassian.net/browse/ATB-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1805: revamped evcs dashboard

dashboards/encrypted-vc-storage/encrypted_vc_storage_dashboard.json
Updated dashboard's SQS tile.
[ATB-1805](https://govukverify.atlassian.net/browse/ATB-1805)
[ATB-1805]: https://govukverify.atlassian.net/browse/ATB-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1805: fixed SQS stats

settings_server_side_service_monitoring.tf
[PSREGOV-900]
[PSREGOV-900]: https://govukverify.atlassian.net/browse/PSREGOV-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> trail new metric Live Service Hub

settings_server_side_service_monitoring.tf
=> fix to calculated metric

dashboards.tf, dashboards/orange/orange-check-hmrc-step-function.json, dashboards/orange/orange-otg-step-function.json
[OJ-2719]
[OJ-2719]: https://govukverify.atlassian.net/browse/OJ-2719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2719: Adds OTG dynatrace dashboard

settings_server_side_service_monitoring.tf
[PSREGOV-900]
[PSREGOV-900]: https://govukverify.atlassian.net/browse/PSREGOV-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> calculated service metric

dashboards/service-health-overview.json, settings_server_side_service_monitoring.tf
=> Updated TSD overview dashboard and amended calc metric

dashboards.tf, dashboards/authentication/authentication_services.json
Authentication Service Dashboard to Monitor all Auth infra services in single dashboard including cloudfront
AUT-3493 &  INCIDEN-820
- [yes ] Is my change backwards compatible? Please include evidence
- [ yes  ] I have tested this and added output to Jira Comment:
- [  ] Documentation added (link) Comment:
=> Adding Authentication Infra service dashboard

slos.tf
=> Added new account to identity proofing and verification service.

dashboards/service-health-overview.json
Updated dashboard to include a new tile for the ReadID Proxy API Gateway, covering 2xx, 4xx and 5xx codes
PSREGOV-992
=> Updated service dashboard for ReadID

settings_service_detection.tf
Replaced "Contains" with "StringContains" in settings_service_detection.tf
[PSREGOV-992/991]
=> PSREGOV-992/991-v2: Replaced "Contains" with "StringContains"

dashboards/service-health-overview.json
Updated the dashboard used by TSD to include separate Mobile section, a link to the Mobile dashboard and added new tiles to the User Experience Monitoring section.
PSREGOV-1046
=> Updated TSD dashboard with mobile metrics

settings_alerting.tf, settings_anomaly_detection.tf
Amending thresholds to assist the AI to generate more realistic baselines to alert off and amended timeframes by which a threshold needs to be breached by.
PSREGOV-855 / PSREGOV-856 / PSREGOV-867
=> Amended global alert settings

service_level_objectives.tf
=> Missed off the count attribute for only deploying to prod

settings_service_detection.tf
Addition of a new service, called HMRC KBV, to be detected by Dynatrace.
PSREGOV-1272
=> Addition of HMRC KBV and testing service naming resource

settings_server_side_service_monitoring.tf
Changes required due to syntax errors and the wrong attribute being used for the operator value
PSREGOV-1416
=> Updated due to syntax error

CODEOWNERS, modules/web_application/key_user_actions.tf
This PR is for adding key user actions for two of our frontend RUM application into IaC, the rest will be added as and when the tickets get picked up.
Second update to this PR is the change from the observability team to the fog team. 
PSREGOV-1381
=> Addition of Key User Actions

dashboards/orange/otg-lambda-metrics.json
Set shared to true
[OJ-2887]
[OJ-2887]: https://govukverify.atlassian.net/browse/OJ-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2887: Set shared to true

dashboards/kiwi/bav-cri.json, dashboards/kiwi/bav-lambda-metrics.json, dashboards/kiwi/sqs-metrics.json
- Fixed section titles
- Resized widgets
[IPS-1212]
[IPS-1212]: https://govukverify.atlassian.net/browse/IPS-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1212: Refine Kiwi Dashboards

modules/web_application/main.tf
There is a discrepancy with regards the TF state file and the resources deployed in the UI, I'm removing the resources from the TF config and I'll then add them back in as part of another PR
=> Removing config due to state and UI discrepancies

dashboards.tf, dashboards/authentication/auth-frontend-sp-migration.json
Monitoring Dashboard for Auth new Frontend -Secure pipeline Migration tech debt 
AUT-3851
- [yes ] Is my change backwards compatible? Please include evidence
- [ no] I have tested this and added output to Jira Comment:
- [ n/a] Documentation added (link) Comment:
=> Monitoring Dashboard for Auth new Frontend

get-accounts.py
=> enable fms waf logs in ct-security-tooling to be sent to dynatrace

modules/web_application/key_user_actions.tf
Addition of key user actions for IPV Core and Authentication RUM applications.
The NonProd and Prod Dynatrace API tokens, stored within the secrets, have been updated due to missing scopes required for deploying these resources.
PSREGOV-1381
=> Auth and IPV Core key user actions

modules/web_application/key_user_actions.tf
Addition of key user actions for the Home, Address and Fraud RUM applications.
PSREGOV-1380 / PSREGOV-1385 / PSREGOV-1386
=> Addition of new key user actions

modules/web_application/key_user_actions.tf
Update to a previous PR as the pipeline failed due to a syntax issue
PSREGOV-1386
=> Updated due to syntax issues with the type attribute

web_applications.tf
Removing the RUM application for HMRC KBV, as the release was pulled and the service is no longer going live
PSREGOV-1390
=> Removed HMRC KBV as it's no longer going live

dashboards.tf, dashboards/authentication/auth-frontend-sp-migration-int.json
AUT-3851: Adding Traffic monitoring for new Auth Integration Env , this dashboard will be used for Migration Auth Integration frontend as part of Secure pipeline Migration 
[AUT-3851]
- [ yes] Is my change backwards compatible? Please include evidence
- [ yes] I have tested this and added output to Jira Comment:
- [n/a ] Documentation added (link) Comment:
[AUT-3851]: https://govukverify.atlassian.net/browse/AUT-3851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-3851: Adding Traffic monitoring for new Auth Integration Env

dashboards/orange/check-hmrc-lambda-metrics.json
[OJ-2708]
[OJ-2708]: https://govukverify.atlassian.net/browse/OJ-2708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2708: Add OTG latency metrics tile

dashboards/orange/accountmanagement-slas-Orange.json
=> Adds key requests to the orange SLAs board

dashboards.tf
The dashboard was deployed out to Dynatrace Production, the GitHub workflow failed.
=> Updated dashboard module reference

dashboards/service-health-overview-tsd.json
Update pushed for the TSD service dashboard as the previous PR to add in the rate aggregation/transformation to the sign-in/sign-up tiles didn't work as expected, there were some lines in the json that also needed changing.
PSREGOV-1938
=> Updated TSD dashboard with new metric expressions

dashboards/spot/key-rotation-dashboard.json
- Add SPOT key rotation dashboard source
[SPT-1110]
[SPT-1110]: https://govukverify.atlassian.net/browse/SPT-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SPT-1110: Check in SPOT key rotation dashboard

modules/web_application/injection_rules.tf, modules/web_application/variables.tf, web_applications.tf
Re-adding injection rules to ensure TF state file and UI are back in sync
PSREGOV-1849
=> Re-adding in injection rules for IPV Core and Home

settings_anomaly_detection.tf
[PSREGOV-2035]
[PSREGOV-2035]: https://govukverify.atlassian.net/browse/PSREGOV-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSREGOV-2035: Removed Aggregation line

.github/dependabot.yml
=> Add Terraform scanning 

.github/workflows/check.yml, .github/workflows/deploy.yml
=> testing new dynatrace debug log feature for PR's

dashboards/orange/address-lambda-metrics.json
=> Add Address Function to lambda dashboard

dashboards/id-check/standard-metrics.json
Update Service Metrics table in ID Check Standard Metrics Dashboard
[DCMAW-12567]
[DCMAW-12567]: https://govukverify.atlassian.net/browse/DCMAW-12567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-12567] Update service metrics table in standards metrics

.github/workflows/check.yml
[PSREGOV-2312](https://govukverify.atlassian.net/browse/PSREGOV-2312)
[PSREGOV-2312]: https://govukverify.atlassian.net/browse/PSREGOV-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Testing with more specific prefix

dashboards/orange/accountmanagement-slas-Orange.json
Update colours for transactions per second tiles
=> Update colours for transactions per second tiles

settings_team_anomaly_detection.tf
TSD were raising incidents due to our alerts coming up as Production Problems in Dynatrace. This PR updates all alert descriptions to associate these alerts with the Control Tower team.
[PSREGOV-2250](https://govukverify.atlassian.net/browse/PSREGOV-2250)
[PSREGOV-2250]: https://govukverify.atlassian.net/browse/PSREGOV-2250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSREGOV 2250 update alert descriptions

dashboards.tf, dashboards/txma/txma-esp-capacity-mgmt-production.json, dashboards/txma/txma-esp-nfrs-production.json
- Make changes to TxMA ESP Capacity Dashboard
- Add new TxMA ESP NFRs Dashboard
[DPT-991](https://govukverify.atlassian.net/browse/DPT-991)
[DPT-991]: https://govukverify.atlassian.net/browse/DPT-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DPT-991 Improve TxMA ESP Dashboards

dashboards/txma/txma-app-health-production.json
reset dashboard by redeploying with updated title and tile name
=> reset txma dashboard by changing title and tile name

dashboards/txma/txma-esp-capacity-mgmt-production.json
Add dashbaords around monthly event volumes
=> add dashboards for event volume

dashboards/core/apigw-metrics.json, dashboards/core/services.json, dashboards/core/sqs-metrics.json, dashboards/core/traffic.json, dashboards/service-level-agreements/core.json
Change ownership of core related dynatrace dashboards to core team
https://govukverify.atlassian.net/browse/PYIC-8273
=> PYIC-8273: Change ownership of dynatrace dashboards to core team

dashboards.tf, dashboards/id-check/lambda-summary.json
Adds json for lambda summary dashboard for id-check team
[DCMAW-12585]
[DCMAW-12585]: https://govukverify.atlassian.net/browse/DCMAW-12585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add lambda summary dashboard for id-check

documents/fpad/fpad-infrastructure.json
Updating FPAD Dashboard for the tickets below.
FPAD-4500, 4502, 4498, 4324, 4322
=> FPAD-4500: Update FPAD Infrastructure dashboard

dashboards.tf, dashboards/id-check/dcmaw-backend-api-gateway.json, dashboards/id-check/dcmaw-backend-lambda.json, dashboards/id-check/dcmaw-frontend-api-gateway.json
- Create new Frontend API dashboard for Prod environment.
- Rename Lambda and Backend API Gateway dashboards to follow new naming conventions.
- Change Lambda and Backend API Gateway module names to reflect name changes.
- Remove unnecessary metric from tile 3 in Backend API Gateway dashboard.
[DCMAW-12633]
[DCMAW-12633]: https://govukverify.atlassian.net/browse/DCMAW-12633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-12633]Add new Frontend API dashboard, rename new dashboards

dashboards.tf, dashboards/id-check/async-backend-completion-rate.json
Create new Async Backend Journey Completion Rate dashboard to be deployed in Production.
[DCMAW-12526]
[DCMAW-12526]: https://govukverify.atlassian.net/browse/DCMAW-12526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DCMAW-12526] Create new Async Journey Completion Rate dashboard 

dashboards/service-health-overview-tsd.json
**Track ReadID errors (4xx, 5xx) and response times.**
[[Ticket](https://govukverify.atlassian.net/browse/PSREGOV-2483)]
=> Adding 4xx-5xx-Latency-Metrics-to-ReadID

dashboards/id-check/async-backend-completion-rate.json
[DCMAW-13064]
[DCMAW-13064]: https://govukverify.atlassian.net/browse/DCMAW-13064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-13064: Update ID Check Async Journey Completion dashboard

dashboards/platform-sre/team-idc-app.tftpl
These are only minor tweaks to query params, no tiles are being removed (despite the confusing git diff)
https://govukverify.atlassian.net/browse/PSREGOV-2609
=> PSREGOV-2609: tweak TEAM app dashboard queries

dashboards/authentication/authentication_services.json
Update Auth services dashboard to include KMS monitoring , removed WAF Monitoring for CloudFront as this now monitored by FMS
[AUT-4429]
- [ yes] Is my change backwards compatible? Please include evidence
- [ yes] I have tested this and added output to Jira Comment:
- [ n/a] Documentation added (link) Comment:
[AUT-4429]: https://govukverify.atlassian.net/browse/AUT-4429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Auth services dashboard to include KMS monitoring

dashboards/txma/txma-app-health-production.json
Removed duplicate event
DPT-1667
=> Removed duplicate tile from TxMA Production Dashboard

documents/fpad/fpad-infrastructure.json
[FPAD-4971]
[FPAD-4971]: https://govukverify.atlassian.net/browse/FPAD-4971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FPAD-4971: Fix SQS events

dashboards/mobile-platform/mobile-platform-behaviours.json, dashboards/mobile-platform/sts/behaviours-dashboards.json
This PR adds the json for the STS and MP dashboards that I have been working on. Do let me know if there is anything else I need to do. I have removed the `popularity` and and `ID` fields. 
[DCMAW-12373]
[DCMAW-12373]: https://govukverify.atlassian.net/browse/DCMAW-12373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-12373 - Added dashboards for STS and MP

dashboards/signin-signup.json
- Add new CRIs
- Restrict data to production
=> BAU: Version control signup/signin graph

dashboards/id-check/async-backend-completion-rate.json, dashboards/id-check/dcmaw-backend-completion-rate.json
Adds a tile for journey completion rate over the last 7 days
[DCMAW-14626]
[DCMAW-14626]: https://govukverify.atlassian.net/browse/DCMAW-14626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-14626: add journey completion rate over time tile

dashboards/orange/address-lambda-metrics.json, dashboards/orange/experian-kbv-lambda-metrics.json
[OJ-2966]
[OJ-2966]: https://govukverify.atlassian.net/browse/OJ-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-2966: Remove java common lambdas from dashboards

dashboards/orange/address-lambda-metrics.json, dashboards/orange/check-hmrc-lambda-metrics.json, dashboards/orange/experian-kbv-lambda-metrics.json
Added Expired JWT tile to Orange CRI Lambda dashboards
[OJ-3249]
[OJ-3249]: https://govukverify.atlassian.net/browse/OJ-3249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OJ-3249: Add Expired JWT tile

dashboards/mobile-platform/sts.json
=> Fixed positioning of tiles

dashboards/authentication/di-auth-notify-delivery-receipts/di-auth-notify-delivery-receipts.json.tpl
We have added a new dimension to the metric.
The change has been tested in Staging and all the panels are displaying the correct data now.  This change is just to a dashboard and does not need to be backward compatible.
=> AUT-4633: Update auth notify dashboard

dashboards/id-check/dcmaw-backend-api-gateway.json, dashboards/id-check/dcmaw-frontend-api-gateway.json
We have a new private API. This changes updates existing tiles to include new api and adds the relevant new tiles.
Also fixes a filter error for the event tick tile in the frontend dashboard
[DCMAW-14871](https://govukverify.atlassian.net/browse/DCMAW-14871)
[DCMAW-14871]: https://govukverify.atlassian.net/browse/DCMAW-14871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-14871: add private-api tiles to backend API dashboard

dashboards.tf, dashboards/authentication/di-auth-notify-delivery-receipts/di-auth-notify-delivery-receipts.json.tpl, dashboards/authentication/di-auth-notify-delivery-receipts/main.tf, dashboards/authentication/di-auth-notify-delivery-receipts/variables.tf
- Convert all metricSelector queries to structured JSON format for better readability
- Add account and environment filtering to prevent cross-account data leakage
- Remove deprecated metricExpressions arrays
- Applied limits to keep the dashboards performant.
AUT-4633
=> AUT-4633: Notify dashboard updates

dashboards/mobile-platform/sts/sts-behaviours.json
Updated the Number of Service Tokens Issued on the STS behaviours dashboard in Dynatrace to show the tokens issued across all services
[DCMAW-15423]
[DCMAW-15423]: https://govukverify.atlassian.net/browse/DCMAW-15423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DCMAW-15423 - Updated dashboard for STS to allow all services to be seen in the filter
